version: '3.8'
services:
  dev-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
    networks:
      - database_assignment
networks:
  database_assignment: